"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UI_EVENTS = exports.ORCH_EVENTS = exports.CONFIG_EVENTS = exports.DOMAIN_EVENTS = void 0;
exports.DOMAIN_EVENTS = {
    AGENT_CREATED: 'agent.created',
    AGENT_REMOVED: 'agent.removed',
    AGENT_STATUS_CHANGED: 'agent.status.changed',
    AGENT_LIFECYCLE_SPAWNING: 'agent.lifecycle.spawning',
    AGENT_LIFECYCLE_SPAWNED: 'agent.lifecycle.spawned',
    AGENT_LIFECYCLE_REMOVING: 'agent.lifecycle.removing',
    AGENT_LIFECYCLE_REMOVED: 'agent.lifecycle.removed',
    TASK_CREATED: 'task.created',
    TASK_ASSIGNED: 'task.assigned',
    TASK_COMPLETED: 'task.completed',
    TASK_FAILED: 'task.failed',
    TASK_STATE_CHANGED: 'task.state.changed',
    TASK_BLOCKED: 'task.blocked',
    TASK_READY: 'task.ready',
    TASK_WAITING: 'task.waiting',
    TASK_DEPENDENCY_ADDED: 'task.dependency.added',
    TASK_DEPENDENCY_REMOVED: 'task.dependency.removed',
    TASK_DEPENDENCY_RESOLVED: 'task.dependency.resolved',
    TASK_SOFT_DEPENDENCY_ADDED: 'task.soft-dependency.added',
    TASK_SOFT_DEPENDENCY_REMOVED: 'task.soft-dependency.removed',
    TASK_SOFT_DEPENDENCY_SATISFIED: 'task.soft-dependency.satisfied',
    TASK_PRIORITY_UPDATED: 'task.priority.updated',
    TASK_CONFLICT_DETECTED: 'task.conflict.detected',
    TASK_CONFLICT_RESOLVED: 'task.conflict.resolved',
    TASK_CONFLICT_DECISION: 'task.conflict.decision',
    TASK_MATCH_SCORE: 'task.match.score',
    THEME_CHANGED: 'theme.changed',
    MESSAGE_RECEIVED: 'message.received',
    CONNECTION_ESTABLISHED: 'connection.established',
    CONNECTION_LOST: 'connection.lost',
    WORKTREE_CREATED: 'worktree.created',
    WORKTREE_REMOVED: 'worktree.removed',
    WORKTREE_MERGED: 'worktree.merged',
    TERMINAL_CREATED: 'terminal.created',
    TERMINAL_CLOSED: 'terminal.closed',
    TERMINAL_DISPOSED: 'terminal.disposed',
    AGENT_TASK_ASSIGNED: 'agent.task.assigned',
    AGENT_TASK_COMPLETED: 'agent.task.completed',
    AGENT_TASK_INTERRUPTED: 'agent.task.interrupted'
};
exports.CONFIG_EVENTS = {
    CONFIG_CHANGED: 'configuration.changed',
    CONFIG_UPDATED: 'configuration.updated',
    CONFIG_VALIDATION_FAILED: 'configuration.validation.failed',
    CONFIG_API_ERROR: 'configuration.api.error',
    CONFIG_UPDATE_FAILED: 'configuration.update.failed',
    CONFIG_BACKED_UP: 'configuration.backed.up',
    CONFIG_RESTORED: 'configuration.restored'
};
exports.ORCH_EVENTS = {
    MESSAGE_RECEIVED: 'orchestration.message.received',
    CLIENT_CONNECTED: 'orchestration.client.connected',
    CLIENT_DISCONNECTED: 'orchestration.client.disconnected',
    SERVER_STARTED: 'orchestration.server.started',
    SERVER_STOPPED: 'orchestration.server.stopped',
    HEARTBEAT_SENT: 'orchestration.heartbeat.sent',
    HEARTBEAT_RECEIVED: 'orchestration.heartbeat.received',
    CONNECTION_TIMEOUT: 'orchestration.connection.timeout',
    MESSAGE_BROADCASTED: 'orchestration.message.broadcasted',
    MESSAGE_TO_DASHBOARD: 'orchestration.message.to_dashboard',
    MESSAGE_DELIVERED: 'orchestration.message.delivered',
    MESSAGE_DELIVERY_FAILED: 'orchestration.message.delivery_failed',
    MESSAGE_TO_AGENTS: 'orchestration.message.to_agents',
    MESSAGE_ACKNOWLEDGED: 'orchestration.message.acknowledged',
    CONNECTION_WELCOME_SENT: 'orchestration.connection.welcome_sent',
    LOGICAL_ID_REGISTERED: 'orchestration.logical_id.registered',
    LOGICAL_ID_UNREGISTERED: 'orchestration.logical_id.unregistered',
    LOGICAL_ID_REASSIGNED: 'orchestration.logical_id.reassigned',
    MESSAGE_PERSISTED: 'orchestration.message.persisted',
    MESSAGE_PERSISTENCE_FAILED: 'orchestration.message.persistence_failed',
    MESSAGE_STORAGE_ROLLED: 'orchestration.message.storage.rolled',
    MESSAGE_STORAGE_CLEANUP: 'orchestration.message.storage.cleanup',
    MESSAGE_ROUTED: 'orchestration.message.routed',
    MESSAGE_VALIDATION_FAILED: 'orchestration.message.validation.failed',
};
exports.UI_EVENTS = {
    UI_STATE_CHANGED: 'ui.state.changed',
    DASHBOARD_STATE_CHANGED: 'dashboard.state.changed',
    TREE_STATE_CHANGED: 'tree.state.changed',
    VIEW_OPENED: 'view.opened',
    VIEW_CLOSED: 'view.closed',
    VIEW_FOCUSED: 'view.focused',
    PANEL_CREATED: 'panel.created',
    PANEL_DISPOSED: 'panel.disposed',
    WEBVIEW_MESSAGE_RECEIVED: 'webview.message.received',
    WEBVIEW_MESSAGE_SENT: 'webview.message.sent',
    TREE_ITEM_SELECTED: 'tree.item.selected',
    TREE_ITEM_EXPANDED: 'tree.item.expanded',
    TREE_ITEM_COLLAPSED: 'tree.item.collapsed',
    TREE_REFRESH_REQUESTED: 'tree.refresh.requested'
};
//# sourceMappingURL=EventConstants.js.map